//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFormCatagory
    {
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public string TotalPermanent { get; set; }
        public string TotalTemporary { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
