//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public Archive()
        {
            this.News = new HashSet<News>();
        }
    
        public int ArchiveId { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
