//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertificateId { get; set; }
        public int ClientId { get; set; }
        public string Standard { get; set; }
        public string CertificateName { get; set; }
        public int StatusId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
    }
}
