//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DASEntities : DbContext
    {
        public DASEntities()
            : base("name=DASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppFormLocationActivity> AppFormLocationActivities { get; set; }
        public DbSet<ApplicationForm> ApplicationForms { get; set; }
        public DbSet<ApplicationFormCatagory> ApplicationFormCatagories { get; set; }
        public DbSet<Archive> Archives { get; set; }
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Label> Labels { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Status_Lng> Status_Lng { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<vw_Clients> vw_Clients { get; set; }
        public DbSet<vw_ClientsBackoffice> vw_ClientsBackoffice { get; set; }
    }
}
